### ISSUE TITLE
Focus management

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#3548]
Raised from https://github.com/TerriaJS/terriajs/pull/3547 we should review how `viewState`'s `topElement` interacts w/ focus/blur across the UI

https://github.com/TerriaJS/terriajs/pull/3547

**Comment by nf-s** [comment]
I don't know if this is relevant to this - but can we also add customisation options for the purple focus outline in mobx:
```css
body {
      *:focus {
        outline: 3px solid #C390F9;
      }
    }
```
