### ISSUE TITLE
Mobx: hover on new ui buttons is way too sensitive

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4308]
A side effect of the changes brought in through https://github.com/TerriaJS/terriajs/pull/4165
Repro:
1. http://ci.terria.io/mobx/
2. hover outside of the target area on right side with any of the MapIconButtons
3. observe that onhover gets triggered depending on how long the button text inside is

**Comment by zoran995** [comment]
If I correctly understood this issue it is easily fixable by adding following on the text inside `ButtonWrapper` 
```
visibility: hidden;
transition: visibility 0s, max-width 0.3s ease,
  margin-right 0.3s ease, opacity 0.3s ease;
```
this way text won't trigger hover and transition will work the same.

**Comment by zoran995** [comment]
If I understand correctly the issue, this can be fixed by updating `MapIconButton` css with
```css
transition: visibility 0.3s ease, max-width 0.3s ease,
                margin-right 0.3s ease, opacity 0.3s ease;
visibility: ${expanded ? `visible` : `hidden`};
```
this will make text hidden unless expanded so it can't trigger expand
