### ISSUE TITLE
Consider setting minimum GITHUB_TOKEN permissions

### ISSUE THREAD

**Issue by chrisdlangton** [TerriaJS/terriajs#6780]
The `GITHUB_TOKEN` is an automatically generated secret to make authenticated calls to the GitHub API. All GH users default to not applying permission sets to the token in their Actions yaml files, and only enterprise plans can enforce a default outside the yaml files.

GitHub themselves [recommend](https://github.com/step-security/secure-repo#1-automatically-set-minimum-github_token-permissions) setting minimum token permissions for the `GITHUB_TOKEN`

### Why is this needed?

- The GITHUB_TOKEN is an automatically generated secret to make authenticated calls to the GitHub API
- If the token is compromised, it can be abused to compromise your environment (e.g., to overwrite releases or source code). This compromise will also impact everyone using your software in their supply chain.

### How to fix this?

[GitHub recommends setting minimum token permissions for the GITHUB_TOKEN](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/).

For complex Action configurations, that are not otherwise documented (the yaml is a kind of documentation but may be hard to reason with for some), It may be a matter of applying trial and error process starting with minimum safe:

```yml
permissions:
  actions: read
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: read
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
```

And change to `read|write|none` based on the needs of each GH Action (looking at the logs to see the causes of failures to gain an understanding of what the Action is doing.
